// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Singulink.Cryptography.Pwned.Service.Models;

#nullable disable

namespace Singulink.Cryptography.Pwned.Service.Migrations
{
    [DbContext(typeof(PwnedDbContext))]
    [Migration("20250423143749_Update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Singulink.Cryptography.Pwned.Service.Models.Password", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("char(40)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("Hash");

                    b.ToTable("Passwords");
                });
#pragma warning restore 612, 618
        }
    }
}
